services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: always
    command: --admin-password "$$2y$$05$$QgoabVnNBN3gR4wezwQovOm0glw00bQvUPORrYxz7.rI/rnw07cBG"
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    #       - ./portainer-data:/data
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.portainer.rule=Host(`$DOMAIN`)'
      - 'traefik.http.routers.portainer.entrypoints=websecure'
      - 'traefik.http.routers.portainer.tls.certresolver=letsencrypt'
      - 'traefik.http.services.portainer.loadbalancer.server.port=9000'

networks:
  proxy:
    external: false
    name: proxy
